---
# SPDX-FileCopyrightText: no
# SPDX-License-Identifier: CC0-1.0
# Configure Gentoo post-install environment (locale-gen, environment updates)
dontChroot: false
timeout: 600
script:
    - command: "env-update"
    - command: "locale-gen"
