from pathlib import Path
from typing import Dict, Any, List
from core.chroot_manager import ChrootManager
from core.logger_setup import setup_logger

logger = setup_logger("portage_manager")

class PortageManagerError(Exception):
    pass

class PortageManager:
    def __init__(self, chroot: ChrootManager, config: Dict[str, Any]):
        self.chroot = chroot
        self.config = config
        self.target_root = chroot.target_root

    def configure_make_conf(self):
        make_conf_path = self.target_root / "etc" / "portage" / "make.conf"
        make_conf_path.parent.mkdir(parents=True, exist_ok=True)

        make_conf_data = self.config.get("make_conf", {})
        use_flags = self.config.get("use_flags", [])

        lines = [
            '# Generated by gentoo-builder',
            'COMMON_FLAGS="' + make_conf_data.get("CFLAGS", "-O2 -pipe -march=x86-64") + '"',
            'CFLAGS="${COMMON_FLAGS}"',
            'CXXFLAGS="${COMMON_FLAGS}"',
            'FCFLAGS="${COMMON_FLAGS}"',
            'FFLAGS="${COMMON_FLAGS}"',
            'MAKEOPTS="' + make_conf_data.get("MAKEOPTS", "-j2") + '"',
            'ACCEPT_KEYWORDS="' + make_conf_data.get("ACCEPT_KEYWORDS", "~amd64") + '"',
            'ACCEPT_LICENSE="' + make_conf_data.get("ACCEPT_LICENSE", "*") + '"',
            'USE="' + " ".join(use_flags) + '"',
            'EMERGE_DEFAULT_OPTS="--jobs=2 --load-average=2"',
            'FEATURES="binpkg-logs parallel-install"'
        ]

        if self.chroot.mode == "mock":
            logger.info(f"[MOCK PORTAGE] Writing make.conf to {make_conf_path}")
        else:
            with open(make_conf_path, "w", encoding="utf-8") as f:
                f.write("\n".join(lines) + "\n")

    def sync_portage(self):
        logger.info("Syncing Portage ebuild repository (emerge-webrsync)...")
        res = self.chroot.run_in_chroot(["emerge-webrsync"])
        if res.returncode != 0 and self.chroot.mode == "real":
            raise PortageManagerError(f"emerge-webrsync failed to sync Portage repository:\n{res.stderr}")

    def install_packages(self, packages: List[str]):
        if not packages:
            return

        logger.info(f"Installing packages via emerge: {' '.join(packages)}")
        cmd = ["emerge", "--noreplace", "--verbose"] + packages
        res = self.chroot.run_in_chroot(cmd)
        if res.returncode != 0 and self.chroot.mode == "real":
            raise PortageManagerError(f"Failed to install packages via emerge:\n{res.stderr}")
