import os
import shutil
from pathlib import Path
from typing import Dict, Any, List
from core.chroot_manager import ChrootManager
from core.logger_setup import setup_logger

logger = setup_logger("portage_manager")

class PortageManagerError(Exception):
    pass

class PortageManager:
    def __init__(self, chroot: ChrootManager, config: Dict[str, Any]):
        self.chroot = chroot
        self.config = config
        self.target_root = chroot.target_root

    def configure_make_conf(self):
        make_conf_path = self.target_root / "etc" / "portage" / "make.conf"
        make_conf_path.parent.mkdir(parents=True, exist_ok=True)

        make_conf_data = self.config.get("make_conf", {})
        use_flags = self.config.get("use_flags", [])

        # Detect host CPU cores dynamically for maximum build performance
        cpu_count = os.cpu_count() or 2
        makeopts = f"-j{cpu_count}"
        load_avg = str(cpu_count)
        emerge_opts = f"--jobs={max(1, cpu_count // 2)} --load-average={load_avg} --ask=n --autounmask-write=y --autounmask-continue=y --getbinpkg=y --usepkg=y"

        # Allow explicit override from config if provided
        cflags = make_conf_data.get("CFLAGS", "-O2 -pipe -march=x86-64")
        makeopts_val = make_conf_data.get("MAKEOPTS") if "MAKEOPTS" in make_conf_data and make_conf_data["MAKEOPTS"] != "-j2" else makeopts

        lines = [
            '# Generated by gentoo-builder (Hardware Optimized)',
            'COMMON_FLAGS="' + cflags + '"',
            'CFLAGS="${COMMON_FLAGS}"',
            'CXXFLAGS="${COMMON_FLAGS}"',
            'FCFLAGS="${COMMON_FLAGS}"',
            'FFLAGS="${COMMON_FLAGS}"',
            f'MAKEOPTS="{makeopts_val}"',
            'ACCEPT_KEYWORDS="' + make_conf_data.get("ACCEPT_KEYWORDS", "~amd64") + '"',
            'ACCEPT_LICENSE="' + make_conf_data.get("ACCEPT_LICENSE", "*") + '"',
            'USE="' + " ".join(use_flags) + '"',
            f'EMERGE_DEFAULT_OPTS="{emerge_opts}"',
            'FEATURES="binpkg-logs parallel-install parallel-fetch buildpkg getbinpkg"',
            'PORTAGE_NICENESS="10"',
            'DISTDIR="/var/cache/distfiles"',
            'PKGDIR="/var/cache/binpkgs"'
        ]

        if self.chroot.mode == "mock":
            logger.info(f"[MOCK PORTAGE] Writing hardware-optimized make.conf to {make_conf_path} (MAKEOPTS={makeopts_val})")
        else:
            logger.info(f"[PORTAGE] Configured make.conf with hardware optimization: MAKEOPTS={makeopts_val}, EMERGE_DEFAULT_OPTS='--jobs={max(1, cpu_count // 2)} --load-average={load_avg}'")
            with open(make_conf_path, "w", encoding="utf-8") as f:
                f.write("\n".join(lines) + "\n")

    def sync_portage(self):
        logger.info("Syncing Portage ebuild repository (emerge-webrsync)...")
        res = self.chroot.run_in_chroot(["emerge-webrsync"])
        if res.returncode != 0 and self.chroot.mode == "real":
            raise PortageManagerError(f"emerge-webrsync failed to sync Portage repository:\n{res.stderr}")

    def update_world(self):
        """Atualiza a árvore world do Gentoo de forma totalmente não-interativa (--ask=n)."""
        logger.info("Atualizando pacotes base e dependências de slot (emerge --ask=n --update --deep --newuse @world)...")
        res = self.chroot.run_in_chroot(["emerge", "--ask=n", "--update", "--deep", "--newuse", "--with-bdeps=y", "@world"])
        if res.returncode != 0 and self.chroot.mode == "real":
            logger.warning(f"emerge @world retornou avisos: {res.stderr}")

    def setup_custom_overlay(self, custom_ebuilds_dir: Path = None):
        """Injeta overlay e ebuilds personalizadas na árvore do Portage chroot."""
        local_repo_dir = self.target_root / "var" / "db" / "repos" / "local_repo"
        repos_conf_dir = self.target_root / "etc" / "portage" / "repos.conf"

        if self.chroot.mode == "mock":
            logger.info("[MOCK PORTAGE] Setting up custom overlay repository")
            return

        repos_conf_dir.mkdir(parents=True, exist_ok=True)
        local_repo_dir.mkdir(parents=True, exist_ok=True)
        (local_repo_dir / "profiles").mkdir(parents=True, exist_ok=True)
        (local_repo_dir / "metadata").mkdir(parents=True, exist_ok=True)

        repo_name_file = local_repo_dir / "profiles" / "repo_name"
        repo_name_file.write_text("local_repo\n")

        layout_conf = local_repo_dir / "metadata" / "layout.conf"
        layout_conf.write_text("masters = gentoo\nauto-sync = no\n")

        local_repo_conf = repos_conf_dir / "local_repo.conf"
        local_repo_conf.write_text(
            "[local_repo]\n"
            "location = /var/db/repos/local_repo\n"
            "masters = gentoo\n"
            "auto-sync = no\n"
        )

        if custom_ebuilds_dir and Path(custom_ebuilds_dir).exists():
            logger.info(f"Copying custom ebuilds from {custom_ebuilds_dir} -> {local_repo_dir}")
            for item in Path(custom_ebuilds_dir).glob("*"):
                if item.is_dir():
                    shutil.copytree(item, local_repo_dir / item.name, dirs_exist_ok=True)
                else:
                    shutil.copy2(item, local_repo_dir / item.name)
            self.chroot.run_in_chroot("ebuild $(find /var/db/repos/local_repo -name '*.ebuild') digest", env={"PORTDIR": "/var/db/repos/gentoo"})

    def install_packages(self, packages: List[str]):
        if not packages:
            return

        self.setup_custom_overlay()
        self.update_world()

        logger.info(f"Installing packages via emerge: {' '.join(packages)}")
        cmd = ["emerge", "--ask=n", "--noreplace", "--verbose", "--autounmask-write=y", "--autounmask-continue=y"] + packages
        res = self.chroot.run_in_chroot(cmd)
        if res.returncode != 0 and self.chroot.mode == "real":
            raise PortageManagerError(f"Failed to install packages via emerge:\n{res.stderr}")
