[global]
   workgroup = WORKGROUP
   server string = Gentoo Modern Live
   server role = standalone server
   obey pam restrictions = yes
   unix password sync = yes
   passwd program = /usr/bin/passwd %u
   passwd chat = *Enter\snew\s*\spassword:* %n\n *Retype\snew\s*\spassword:* %n\n *password\supdated\ssuccessfully* .
   pam password change = yes
   map to guest = bad user
   usershare allow guests = yes
   usershare max shares = 100
   usershare owner only = false
   client min protocol = NT1
   client max protocol = SMB3
   server min protocol = NT1
   ntlm auth = yes
   local master = yes
   preferred master = yes
   os level = 20
   dns proxy = no

[Public]
   comment = Public Shared Folder
   path = /home/live/Public
   browseable = yes
   read only = no
   guest ok = yes
   create mask = 0777
   directory mask = 0777
